- replace:
    path: /usr/local/etc/snort/snort.lua
    regexp: '(--\[\[[\s\S]reputation((.|\n)*?)\]\])'
    replace: |-
      reputation =
      {
          blocklist = BLACK_LIST_PATH .. "/default.blocklist",
      }

      search_engine = { search_method = "hyperscan" }

      detection = { 
          hyperscan_literals = true, 
          pcre_to_regex = true
      }

- name: set HOME_NET
  lineinfile:
    path: /usr/local/etc/snort/snort.lua
    regexp: "HOME_NET = "
    line: "HOME_NET = '192.168.0.0/24'"
    backrefs: yes
